version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A habits_project worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
