version: '3.9'
services:
  django:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=habits_project.settings
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    entrypoint: /usr/local/bin/docker-entrypoint.sh

  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7

  celery:
    build: .
    tty: true
    command: poetry run celery -A habits_project worker -l INFO
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - django
      - redis

  celery_beat:
    build: .
    tty: true
    command: poetry run celery -A habits_project beat -l INFO
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - django
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/app.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  postgres_data: